#!/usr/bin/env node
/**
 * Tool-types codegen — both a library function and a CLI binary.
 *
 * Library: {@link runCodegen} walks an array of `ToolCollectionExport`,
 * runs each tool's input/output Zod schema through `z.toJSONSchema()` and
 * `json-schema-to-typescript`, and returns a single `.d.ts` blob plus a
 * list of any schemas that fell back to generic types.
 *
 * Binary: when invoked directly (`umbraco-mcp-generate-types`), the file
 * dynamic-imports the consumer's compiled `dist/collections.js`, calls
 * `runCodegen`, and writes the output to `dist/tool-types.d.ts`. The
 * shebang on line 1 + `bin` entry in package.json make this runnable
 * via `npx umbraco-mcp-generate-types`.
 *
 * See `docs/plans/mcp-server-sdk/tool-types-codegen.md` and
 * `17/umbraco-in-ai/mcp/base-mcp/sdk/tool-types.md` (UmbracoDocs) for
 * full usage, options, and consumer wiring.
 */
import { z } from "zod";
import { compile } from "json-schema-to-typescript";
import type { ToolCollectionExport } from "../types/tool-collection.js";
import type { ToolDefinition } from "../types/tool-definition.js";
import { createPermissiveCodegenUser } from "./permissive-user.js";

export interface RunCodegenOptions {
  /** Collections to walk (already imported, not a path). */
  collections: ToolCollectionExport[];
  /** Name of the emitted registry interface (e.g. "CmsTools"). */
  registryName: string;
}

export interface SkippedSchema {
  tool: string;
  field: "input" | "output";
  err: string;
}

export interface RunCodegenResult {
  /** The full `.d.ts` file content, ready to write to disk. */
  output: string;
  /** Number of tools processed (sum across all collections). */
  toolsProcessed: number;
  /** Per-tool/per-field schema conversions that fell back to a generic type. */
  skipped: SkippedSchema[];
}

function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((p) => (p.length === 0 ? "" : p[0].toUpperCase() + p.slice(1)))
    .join("");
}

function toJsonSchema(schemaOrShape: unknown): unknown {
  if (schemaOrShape === undefined || schemaOrShape === null) return null;
  if (typeof schemaOrShape !== "object") {
    throw new Error(
      `Invalid schema: expected a ZodType or plain-object ZodRawShape, got ${typeof schemaOrShape}`,
    );
  }
  // ZodType has a `_def`; ZodRawShape is a plain object whose values are ZodTypes.
  const wrapped =
    "_def" in (schemaOrShape as Record<string, unknown>)
      ? (schemaOrShape as z.ZodType)
      : z.object(schemaOrShape as z.ZodRawShape);
  return z.toJSONSchema(wrapped, { target: "draft-2020-12" });
}

export async function runCodegen(
  options: RunCodegenOptions,
): Promise<RunCodegenResult> {
  const { collections, registryName } = options;
  const permissiveUser = createPermissiveCodegenUser();

  // 1. Flatten tools across collections.
  const tools: ToolDefinition[] = [];
  for (const collection of collections) {
    const ts =
      typeof collection.tools === "function"
        ? collection.tools(permissiveUser)
        : (collection.tools as ToolDefinition[]);
    for (const t of ts) tools.push(t);
  }

  const lines: string[] = [
    "// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk → umbraco-mcp-generate-types",
    "// Do not edit by hand. Regenerate after every build.",
    "",
  ];
  const registryEntries: string[] = [];
  const skipped: SkippedSchema[] = [];
  const seenTypeNames = new Map<string, string>();

  for (const tool of tools) {
    const inputTypeName = `${pascal(tool.name)}Input`;
    const outputTypeName = `${pascal(tool.name)}Output`;

    const collidingName = seenTypeNames.has(inputTypeName)
      ? inputTypeName
      : seenTypeNames.has(outputTypeName)
        ? outputTypeName
        : null;
    if (collidingName !== null) {
      const previousTool = seenTypeNames.get(collidingName)!;
      throw new Error(
        `[tool-types] Type name collision for tool "${tool.name}": ` +
          `produces "${collidingName}", already claimed by "${previousTool}". ` +
          `Rename one or prefix with collection.`,
      );
    }
    seenTypeNames.set(inputTypeName, tool.name);
    seenTypeNames.set(outputTypeName, tool.name);

    let inputTs = "Record<string, unknown>";
    let outputTs = "unknown";

    try {
      // `schema` is a deprecated alias for `inputSchema`.
      const inputSchema = toJsonSchema(
        tool.inputSchema ?? (tool as { schema?: unknown }).schema,
      );
      if (inputSchema) {
        const compiled = await compile(inputSchema as object, inputTypeName, {
          bannerComment: "",
          additionalProperties: false,
          unreachableDefinitions: true,
        });
        lines.push(compiled.trim(), "");
        inputTs = inputTypeName;
      }
    } catch (err) {
      skipped.push({
        tool: tool.name,
        field: "input",
        err: err instanceof Error ? err.message : String(err),
      });
    }

    try {
      const outputSchema = toJsonSchema(tool.outputSchema);
      if (outputSchema) {
        const compiled = await compile(outputSchema as object, outputTypeName, {
          bannerComment: "",
          additionalProperties: true,
          unreachableDefinitions: true,
        });
        lines.push(compiled.trim(), "");
        outputTs = outputTypeName;
      }
    } catch (err) {
      skipped.push({
        tool: tool.name,
        field: "output",
        err: err instanceof Error ? err.message : String(err),
      });
    }

    registryEntries.push(
      `  ${JSON.stringify(tool.name)}: { input: ${inputTs}; output: ${outputTs} };`,
    );
  }

  lines.push(
    `export interface ${registryName} {`,
    ...registryEntries,
    "}",
    "",
    `export type ${registryName}Name = keyof ${registryName};`,
    "",
  );

  return {
    output: lines.join("\n"),
    toolsProcessed: tools.length,
    skipped,
  };
}

// ---------------------------------------------------------------------------
// CLI entry-point
// ---------------------------------------------------------------------------

async function mainFromCli(argv: string[]): Promise<void> {
  const { parseArgs } = await import("node:util");
  const { resolve, dirname } = await import("node:path");
  const { writeFileSync, mkdirSync, readFileSync } = await import("node:fs");
  const { pathToFileURL } = await import("node:url");

  const { values } = parseArgs({
    args: argv,
    options: {
      collections: { type: "string", default: "./dist/collections.js" },
      out: { type: "string", default: "./dist/tool-types.d.ts" },
      "registry-name": { type: "string" },
      help: { type: "boolean", short: "h", default: false },
    },
    strict: true,
  });

  if (values.help) {
    console.log(
      [
        "Usage: umbraco-mcp-generate-types [options]",
        "",
        "Options:",
        "  --collections <path>    Path to compiled collections module (default ./dist/collections.js)",
        "  --out <path>            Output .d.ts path (default ./dist/tool-types.d.ts)",
        "  --registry-name <name>  Registry interface name (default derived from package.json name)",
        "  -h, --help              Show this help",
      ].join("\n"),
    );
    return;
  }

  const collectionsPath = resolve(process.cwd(), values.collections as string);
  const outPath = resolve(process.cwd(), values.out as string);

  // Resolve registry name. Priority: --registry-name > deriving from package.json.
  let registryName = values["registry-name"] as string | undefined;
  if (!registryName) {
    try {
      const pkg = JSON.parse(
        readFileSync(resolve(process.cwd(), "package.json"), "utf8"),
      );
      // "@umbraco-cms/mcp-cms" → "McpCmsTools" — strip scope, PascalCase, append Tools.
      const baseName = String(pkg.name ?? "Mcp").replace(/^@[^/]+\//, "");
      registryName = `${pascal(baseName)}Tools`;
    } catch {
      registryName = "Tools";
    }
  }

  // Dynamic import of the consumer's compiled collections.
  const mod = await import(pathToFileURL(collectionsPath).href);
  const collections =
    (mod as { collections?: unknown; default?: unknown }).collections ??
    (mod as { default?: unknown }).default;

  if (!Array.isArray(collections)) {
    throw new Error(
      `[tool-types] ${collectionsPath} must export a "collections" array (or default-export one). ` +
        `Got: ${typeof collections}`,
    );
  }

  const result = await runCodegen({
    collections: collections as ToolCollectionExport[],
    registryName,
  });

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, result.output, "utf8");

  if (result.skipped.length > 0) {
    console.warn(
      `[tool-types] ${result.skipped.length} schema(s) fell back to generic types:`,
    );
    for (const s of result.skipped) {
      console.warn(`  - ${s.tool} (${s.field}): ${s.err}`);
    }
  }
  console.log(
    `[tool-types] Wrote ${result.toolsProcessed} tools → ${outPath}`,
  );
}

// Detect "called as a binary" without breaking when the file is imported
// for testing. `process.argv[1]` is the script path Node was started with;
// `pathToFileURL` normalises it to compare with `import.meta.url`.
import { pathToFileURL as _pathToFileURL } from "node:url";

const _isMain =
  !!process.argv[1] &&
  import.meta.url === _pathToFileURL(process.argv[1]).href;

if (_isMain) {
  mainFromCli(process.argv.slice(2)).catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
