// packages/mcp-server-sdk/src/cli/generate-tool-types.ts
import { z } from "zod";
import { compile } from "json-schema-to-typescript";
import type { ToolCollectionExport } from "../types/tool-collection.js";
import type { ToolDefinition } from "../types/tool-definition.js";
import { createPermissiveCodegenUser } from "./permissive-user.js";

export interface RunCodegenOptions {
  /** Collections to walk (already imported, not a path). */
  collections: ToolCollectionExport[];
  /** Name of the emitted registry interface (e.g. "CmsTools"). */
  registryName: string;
}

export interface SkippedSchema {
  tool: string;
  field: "input" | "output";
  err: string;
}

export interface RunCodegenResult {
  /** The full `.d.ts` file content, ready to write to disk. */
  output: string;
  /** Number of tools processed (sum across all collections). */
  toolsProcessed: number;
  /** Per-tool/per-field schema conversions that fell back to a generic type. */
  skipped: SkippedSchema[];
}

function pascal(name: string): string {
  return name
    .split(/[-_]/)
    .map((p) => (p.length === 0 ? "" : p[0].toUpperCase() + p.slice(1)))
    .join("");
}

function toJsonSchema(schemaOrShape: unknown): unknown {
  if (schemaOrShape === undefined || schemaOrShape === null) return null;
  if (typeof schemaOrShape !== "object") {
    throw new Error(
      `Invalid schema: expected a ZodType or plain-object ZodRawShape, got ${typeof schemaOrShape}`,
    );
  }
  // ZodType has a `_def`; ZodRawShape is a plain object whose values are ZodTypes.
  const wrapped =
    "_def" in (schemaOrShape as Record<string, unknown>)
      ? (schemaOrShape as z.ZodType)
      : z.object(schemaOrShape as z.ZodRawShape);
  return z.toJSONSchema(wrapped, { target: "draft-2020-12" });
}

export async function runCodegen(
  options: RunCodegenOptions,
): Promise<RunCodegenResult> {
  const { collections, registryName } = options;
  const permissiveUser = createPermissiveCodegenUser();

  // 1. Flatten tools across collections.
  const tools: ToolDefinition[] = [];
  for (const collection of collections) {
    const ts =
      typeof collection.tools === "function"
        ? collection.tools(permissiveUser)
        : (collection.tools as ToolDefinition[]);
    for (const t of ts) tools.push(t);
  }

  const lines: string[] = [
    "// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk → umbraco-mcp-generate-types",
    "// Do not edit by hand. Regenerate after every build.",
    "",
  ];
  const registryEntries: string[] = [];
  const skipped: SkippedSchema[] = [];
  const seenTypeNames = new Map<string, string>();

  for (const tool of tools) {
    const inputTypeName = `${pascal(tool.name)}Input`;
    const outputTypeName = `${pascal(tool.name)}Output`;

    const collidingName = seenTypeNames.has(inputTypeName)
      ? inputTypeName
      : seenTypeNames.has(outputTypeName)
        ? outputTypeName
        : null;
    if (collidingName !== null) {
      const previousTool = seenTypeNames.get(collidingName)!;
      throw new Error(
        `[tool-types] Type name collision for tool "${tool.name}": ` +
          `produces "${collidingName}", already claimed by "${previousTool}". ` +
          `Rename one or prefix with collection.`,
      );
    }
    seenTypeNames.set(inputTypeName, tool.name);
    seenTypeNames.set(outputTypeName, tool.name);

    let inputTs = "Record<string, unknown>";
    let outputTs = "unknown";

    try {
      // `schema` is a deprecated alias for `inputSchema`.
      const inputSchema = toJsonSchema(
        tool.inputSchema ?? (tool as { schema?: unknown }).schema,
      );
      if (inputSchema) {
        const compiled = await compile(inputSchema as object, inputTypeName, {
          bannerComment: "",
          additionalProperties: false,
          unreachableDefinitions: true,
        });
        lines.push(compiled.trim(), "");
        inputTs = inputTypeName;
      }
    } catch (err) {
      skipped.push({
        tool: tool.name,
        field: "input",
        err: err instanceof Error ? err.message : String(err),
      });
    }

    try {
      const outputSchema = toJsonSchema(tool.outputSchema);
      if (outputSchema) {
        const compiled = await compile(outputSchema as object, outputTypeName, {
          bannerComment: "",
          additionalProperties: true,
          unreachableDefinitions: true,
        });
        lines.push(compiled.trim(), "");
        outputTs = outputTypeName;
      }
    } catch (err) {
      skipped.push({
        tool: tool.name,
        field: "output",
        err: err instanceof Error ? err.message : String(err),
      });
    }

    registryEntries.push(
      `  ${JSON.stringify(tool.name)}: { input: ${inputTs}; output: ${outputTs} };`,
    );
  }

  lines.push(
    `export interface ${registryName} {`,
    ...registryEntries,
    "}",
    "",
    `export type ${registryName}Name = keyof ${registryName};`,
    "",
  );

  return {
    output: lines.join("\n"),
    toolsProcessed: tools.length,
    skipped,
  };
}
