/**
 * Vite config helper for bundling MCP App widgets into single-file HTML
 * blobs that an MCP server can ship inline.
 *
 * Consumer flow:
 *
 * 1. Author a widget at `widgets/<name>/{index.html, main.ts}`.
 * 2. Add a build step that runs `umbraco-mcp-widgets build`
 *    (or programmatically calls `buildWidgets`).
 * 3. The CLI emits `widgets/<name>/dist-html.generated.ts` containing
 *    `WIDGET_HTML` and `WIDGET_URI` exports.
 * 4. Pass `WIDGET_HTML` / `WIDGET_URI` to `registerConfirmedTool` (or your
 *    own registerAppTool / registerAppResource calls).
 *
 * The single-file output is intentional: hosts read the HTML inline from
 * the MCP `resources/read` payload, so any bundler that emits separate
 * chunks won't load.
 *
 * @module widget-build
 */

import { realpathSync } from "node:fs";
import type { InlineConfig } from "vite";

/**
 * Default URI scheme used by `registerConfirmedTool` and the built-in
 * confirm-dialog widget. Consumers can pick any `ui://` scheme they want.
 */
export const DEFAULT_WIDGET_URI_PREFIX = "ui://umbraco-mcp/widgets/";

export interface WidgetBuildOptions {
  /**
   * Absolute path to the directory containing `index.html`.
   */
  inputDir: string;
  /**
   * Public URI the host will read this widget from. Must start with `ui://`.
   */
  uri: string;
  /**
   * Optional Vite overrides merged on top of the singlefile defaults.
   */
  vite?: InlineConfig;
}

/**
 * Build a Vite `InlineConfig` that bundles the widget into a single HTML
 * file in-memory (no on-disk emit). Pair with `vite.build()` and read
 * the result from the returned `RollupOutput`.
 */
export async function createWidgetViteConfig(
  options: WidgetBuildOptions,
): Promise<InlineConfig> {
  const { viteSingleFile } = await import("vite-plugin-singlefile");

  // Resolve symlinks so the input directory and rolldown's resolved entry
  // (which uses realpath) live under the same prefix. Otherwise on macOS,
  // `/var/...` ≠ `/private/var/...` confuses Rolldown's relative-path check.
  const root = realpathSync(options.inputDir);

  const base: InlineConfig = {
    root,
    configFile: false,
    logLevel: "warn",
    plugins: [viteSingleFile({ removeViteModuleLoader: true })],
    build: {
      target: "es2022",
      cssCodeSplit: false,
      assetsInlineLimit: Number.MAX_SAFE_INTEGER,
      rollupOptions: {
        input: "index.html",
      },
      write: false,
      emptyOutDir: false,
      reportCompressedSize: false,
    },
  };

  return mergeConfigs(base, options.vite);
}

/**
 * Build a single widget and return the bundled HTML as a string.
 */
export async function buildWidgetHtml(
  options: WidgetBuildOptions,
): Promise<string> {
  const { build } = await import("vite");
  const config = await createWidgetViteConfig(options);
  const result = await build(config);
  const output = Array.isArray(result)
    ? result[0]
    : "output" in result
      ? result
      : null;
  if (!output) {
    throw new Error(
      "vite build returned a watcher; widget builds must be one-shot",
    );
  }
  const htmlAsset = output.output.find(
    (asset) => asset.type === "asset" && asset.fileName.endsWith(".html"),
  );
  if (!htmlAsset || htmlAsset.type !== "asset") {
    throw new Error(
      `widget build produced no HTML output for ${options.inputDir}`,
    );
  }
  return typeof htmlAsset.source === "string"
    ? htmlAsset.source
    : new TextDecoder().decode(htmlAsset.source as Uint8Array);
}

/**
 * Wrap a built HTML blob and its URI as a TypeScript module source string.
 * Caller is responsible for writing the result to disk.
 */
export function renderWidgetModuleSource(params: {
  html: string;
  uri: string;
  /** Identifier prefix for the exports — defaults to `WIDGET`. */
  exportPrefix?: string;
  /** Optional banner; e.g. "// AUTO-GENERATED — do not edit". */
  banner?: string;
}): string {
  const prefix = params.exportPrefix ?? "WIDGET";
  const banner =
    params.banner ??
    "// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk widget-build — do not edit by hand.";
  return `${banner}

export const ${prefix}_URI = ${JSON.stringify(params.uri)};
export const ${prefix}_HTML = ${JSON.stringify(params.html)};
`;
}

function mergeConfigs(
  base: InlineConfig,
  override: InlineConfig | undefined,
): InlineConfig {
  if (!override) return base;
  return {
    ...base,
    ...override,
    plugins: [...(base.plugins ?? []), ...(override.plugins ?? [])],
    build: { ...base.build, ...override.build },
  };
}
