#!/usr/bin/env node
/**
 * MCP Server Entry Point
 *
 * This file sets up and starts the MCP server.
 * Customize this to add your tool collections.
 */

import "./load-env.js";
import { McpServer, type ToolCallback } from "@modelcontextprotocol/sdk/server/mcp.js";
import packageJson from "../package.json" with { type: "json" };
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import {
  configureApiClient,
  initializeUmbracoFetch,
  createToolAnnotations,
  discoverProxiedTools,
  parseProxiedToolName,
  createCollectionConfigLoader,
  shouldIncludeTool,
  handleCliCommands,
  checkUmbracoVersion,
  configureVersionCheckHook,
  getVersionCheckMessage,
  UmbracoManagementClient,
  CAPTURE_RAW_HTTP_RESPONSE,
  SERVER_INFORMATION_PATH,
  type CollectionConfiguration,
  type HttpResponse,
} from "@umbraco-cms/mcp-server-sdk";

// Import the Orval-generated API client
import { getExampleUmbracoAddOnAPI } from "./umbraco-api/api/generated/exampleApi.js";

// Import tool collections
import exampleCollection from "./umbraco-api/tools/example/index.js";
import example2Collection from "./umbraco-api/tools/example-2/index.js";
import chainedCollection from "./umbraco-api/tools/chained/index.js";

// Import MCP client manager (for chaining to other MCP servers)
import { mcpClientManager } from "./umbraco-api/mcp-client.js";

// Import MCP server chain configuration
import { mcpServers } from "./config/mcp-servers.js";

// Import registries for tool filtering
import {
  allModes,
  allModeNames,
  allSliceNames,
  loadServerConfig,
  clearConfigCache,
  UMBRACO_TARGET_MAJOR,
} from "./config/index.js";

// Initialize the SDK's fetch client for real Umbraco API calls.
// This enables the Orval-generated client to authenticate via client_credentials.
const baseUrl = process.env.UMBRACO_BASE_URL || "http://localhost:44391";
const clientId = process.env.UMBRACO_CLIENT_ID || "";
const clientSecret = process.env.UMBRACO_CLIENT_SECRET || "";
const headerName = process.env.UMBRACO_MCP_HEADER_NAME;
const headerValue = process.env.UMBRACO_MCP_HEADER_VALUE;
if (clientId) {
  initializeUmbracoFetch({ baseUrl, clientId, clientSecret, headerName, headerValue });
}

// Configure the API client for use with toolkit helpers
// This connects your generated Orval client to executeGetApiCall, executeVoidApiCall, etc.
configureApiClient(() => getExampleUmbracoAddOnAPI());

// ============================================================================
// Tool Filtering Setup
// ============================================================================

// Clear config cache to ensure fresh config for each server start
clearConfigCache();

// Load server configuration (includes filtering settings from env vars)
const serverConfig = await loadServerConfig(true);

// Create collection config loader with our registries
const configLoader = createCollectionConfigLoader({
  modeRegistry: allModes,
  allModeNames,
  allSliceNames,
});

// Load filtering configuration from server config
const filterConfig: CollectionConfiguration = configLoader.loadFromConfig(serverConfig.umbraco);

// ============================================================================
// CLI Introspection (runs before server start, exits immediately)
// ============================================================================

const collections = [exampleCollection, example2Collection, chainedCollection];

// handleCliCommands checks --list-tools, --describe-tool, --generate-context, --call.
// If any flag is set it prints output and calls process.exit(0).
// Otherwise it returns and the server continues to start.
await handleCliCommands(collections, {
  cliFlags: serverConfig.cliFlags,
  serverName: "my-umbraco-mcp",
  serverVersion: packageJson.version,
  filterConfig,
  serverConfig: serverConfig.umbraco,
});

// ============================================================================
// Version Check
// ============================================================================
//
// Verify the connected Umbraco major version matches the major version this
// server's tools were generated against. `expectedUmbracoMajor` is a required
// SDK field, so this can't be silently left off.
//
// The value comes from `UMBRACO_TARGET_MAJOR` in
// `config/umbraco-target.generated.ts` — auto-generated by `npm run generate`,
// which reads it from the Umbraco instance in `.env` (the spec cannot supply it:
// every Umbraco spec hard-codes `info.version` to "Latest"). Regenerate against
// a newer Umbraco and the constant follows automatically; there is nothing to
// keep in sync by hand. `UMBRACO_EXPECTED_MAJOR` /
// `--umbraco-expected-major` (see `config/server-config.ts`) overrides it at
// runtime for a project deliberately targeting a different Umbraco major.
//
// It deliberately does *not* compare against this package's own version:
// a new project starts at "1.0.0", which says nothing about which Umbraco
// major it targets, so an implicit comparison falsely blocked the first tool
// call of every new server (see Umbraco-MCP-Base#220).
//
// `checkUmbracoVersion` never throws and always logs a mismatch/error to
// stderr (console.error — stdio-transport safe), but that alone isn't enough
// to surface the warning to the user or pause tool execution. Two more calls
// close that gap:
//   - `configureVersionCheckHook()` bridges the result into
//     `withPreExecutionCheck` (applied to every tool via
//     `withStandardDecorators`), so a mismatch blocks the first tool call
//     with the warning until the user deliberately retries. Safe to call
//     unconditionally — it never blocks anything when the versions match.
//   - `getVersionCheckMessage()` lets us fold the same warning into the
//     server's `instructions`, so it reaches the model/user directly rather
//     than only the server log.
// Skipped when no client credentials are configured (matches the
// `initializeUmbracoFetch` gate above) so CLI introspection / offline usage
// never makes a live network call.
if (clientId) {
  await checkUmbracoVersion({
    mcpVersion: packageJson.version,
    expectedUmbracoMajor: serverConfig.custom.expectedUmbracoMajor ?? UMBRACO_TARGET_MAJOR,
    client: {
      getServerInformation: async () => {
        const response = (await UmbracoManagementClient<{ version: string }>(
          { url: SERVER_INFORMATION_PATH, method: "GET" },
          CAPTURE_RAW_HTTP_RESPONSE,
        )) as unknown as HttpResponse<{ version: string }>;
        return { version: response.data.version };
      },
    },
  });
  configureVersionCheckHook();
}

const versionCheckMessage = getVersionCheckMessage();

// ============================================================================
// MCP Server Setup
// ============================================================================

// Create MCP server.
// Pass an optional `instructions` string in the second argument to send
// server-level guidance to clients during `initialize`. Most clients fold
// this into the model's system prompt, so it applies implicitly without
// per-tool repetition. Mirror the same value in `worker.ts` so stdio and
// hosted deployments behave consistently.
//
// Here it's used to surface a version-mismatch warning when one was detected
// (null otherwise). Extend the string if you also want custom guidance, e.g.:
// [versionCheckMessage, "Refer to items by name, not by ID."].filter(Boolean).join("\n\n")
const server = new McpServer(
  { name: "my-umbraco-mcp", version: packageJson.version },
  versionCheckMessage ? { instructions: versionCheckMessage } : undefined,
);

// ============================================================================
// Register Tools with Filtering
// ============================================================================

let registeredToolCount = 0;

for (const collection of collections) {
  const collectionName = collection.metadata.name;

  // Get tools for current user (pass user context if needed)
  const tools = collection.tools({});

  for (const tool of tools) {
    // Check if tool should be included based on filtering config
    if (!shouldIncludeTool(tool, { collectionName, config: filterConfig })) {
      continue;
    }

    // Build annotations from tool definition
    const annotations = createToolAnnotations(tool);

    // Register tool with MCP server using registerTool API
    server.registerTool(tool.name, {
      description: tool.description,
      inputSchema: tool.inputSchema,
      outputSchema: tool.outputSchema,
      annotations,
    }, tool.handler as ToolCallback<typeof tool.inputSchema>);

    registeredToolCount++;
  }
}

// Start the server
async function main() {
  // Discover and register proxied tools from chained MCP servers
  // Skip if chaining is disabled via config (DISABLE_MCP_CHAINING=true)
  const chainingEnabled = mcpServers.length > 0 && !serverConfig.custom.disableMcpChaining;

  if (chainingEnabled) {
    try {
      const proxiedTools = await discoverProxiedTools(mcpClientManager);

      for (const pt of proxiedTools) {
        // Register proxied tool with forwarding handler
        // Note: We don't pass inputSchema since validation happens on the chained server
        // and the MCP SDK expects Zod schemas, not raw JSON Schema objects
        server.registerTool(
          pt.prefixedName,
          {
            description: `[Proxied from ${pt.serverName}] ${pt.originalTool.description || "No description"}`,
          },
          async (args: Record<string, unknown>): Promise<CallToolResult> => {
            const { serverName, toolName } = parseProxiedToolName(pt.prefixedName);
            const result = await mcpClientManager.callTool(serverName, toolName, args);
            return result as CallToolResult;
          }
        );
      }

      if (proxiedTools.length > 0) {
        console.error(`Registered ${proxiedTools.length} proxied tool(s) from chained MCP servers`);
      }
    } catch (error) {
      console.error("Warning: Failed to discover proxied tools:", error);
      // Continue without proxied tools - local tools still work
    }
  }

  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(`MCP Server started with ${registeredToolCount} tool(s) from ${collections.length} collection(s)`);
}

// Cleanup on shutdown
process.on("SIGINT", async () => {
  await mcpClientManager.disconnectAll();
  process.exit(0);
});

process.on("SIGTERM", async () => {
  await mcpClientManager.disconnectAll();
  process.exit(0);
});

main().catch((error) => {
  console.error("Failed to start MCP server:", error);
  process.exit(1);
});
