/**
 * Configuration Exports
 *
 * Re-exports slice and mode registries for use throughout the project.
 */

export {
  toolSliceNames,
  allSliceNames,
  type ToolSliceName,
  type ExtendedSliceName,
} from "./slice-registry.js";

export {
  toolModes,
  allModes,
  allModeNames,
  type ToolModeName,
} from "./mode-registry.js";

export {
  loadServerConfig,
  clearConfigCache,
  getCustomFieldDefinitions,
  type ServerConfig,
  type MyServerCustomConfig,
} from "./server-config.js";

// Generated by `npm run generate` (orval) from the spec's `info.version` —
// see the target-major transformer wired up in orval.config.ts.
export { UMBRACO_TARGET_MAJOR } from "./umbraco-target.generated.js";
