/**
 * Configuration Exports
 *
 * Re-exports slice and mode registries for use throughout the project.
 */

export {
  toolSliceNames,
  allSliceNames,
  type ToolSliceName,
  type ExtendedSliceName,
} from "./slice-registry.js";

export {
  toolModes,
  allModes,
  allModeNames,
  type ToolModeName,
} from "./mode-registry.js";

export {
  loadServerConfig,
  clearConfigCache,
  getCustomFieldDefinitions,
  type ServerConfig,
  type MyServerCustomConfig,
} from "./server-config.js";

// Generated by `npm run generate` — `umbraco-mcp-stamp-target-major` runs after
// orval and resolves the major from an explicit `--major`, else the connected
// Umbraco (GET /umbraco/management/api/v1/server/information), and only as a
// last resort the `--spec` document's `info.version`. The instance is the
// normal source: every Umbraco-served spec hard-codes `info.version` to
// "Latest".
export { UMBRACO_TARGET_MAJOR } from "./umbraco-target.generated.js";
