// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk's orval target-major transformer.
// Do not edit by hand — regenerate via `npm run generate`.
/**
 * The Umbraco major version this server's generated tools target.
 *
 * Derived from the `info.version` of the OpenAPI spec that `orval.config.ts`
 * points at.
 *
 * Reported version: 17.4.0.
 *
 * Passed to `checkUmbracoVersion` at startup, which blocks tool execution when
 * the connected instance's major differs. Set `UMBRACO_EXPECTED_MAJOR` (or
 * `--umbraco-expected-major`) to override it at runtime when deliberately
 * pointing at a different Umbraco major.
 */
export const UMBRACO_TARGET_MAJOR = "17";
