// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk's orval target-major transformer.
// Do not edit by hand — regenerate via `npm run generate`.
/**
 * The Umbraco major version this server's generated tools target.
 *
 * Derived from the `info.version` of the OpenAPI spec that `orval.config.ts`
 * points at (`info.version`: 17.4.0), so it always matches the tool surface that was
 * actually generated. Regenerating against a different Umbraco updates it
 * here automatically — there is nothing to keep in sync by hand.
 *
 * Passed to `checkUmbracoVersion` at startup. Set `UMBRACO_EXPECTED_MAJOR`
 * (or `--umbraco-expected-major`) to override it at runtime when deliberately
 * pointing at a different Umbraco major.
 */
export const UMBRACO_TARGET_MAJOR = "17";
