// AUTO-GENERATED by @umbraco-cms/mcp-server-sdk's orval target-major transformer.
// Do not edit by hand — regenerate via `npm run generate`.
/**
 * The Umbraco major version this server's generated tools target.
 *
 * Placeholder committed with the project scaffold so it compiles before
 * anything has been generated. NOT reported by any Umbraco — run `npm run
 * generate` against your instance to replace it.
 *
 * Passed to `checkUmbracoVersion` at startup, which blocks tool execution when
 * the connected instance's major differs. Set `UMBRACO_EXPECTED_MAJOR` (or
 * `--umbraco-expected-major`) to override it at runtime when deliberately
 * pointing at a different Umbraco major.
 */
export const UMBRACO_TARGET_MAJOR = "17";
